#!/usr/bin/env bash

# ThePrimeagen's tmux-sessionizer
# Quickly switch between projects using fzf

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Customize these paths to your project directories
    selected=$(find ~/Developer/github ~/Developer/mit-dev/code ~/ ~/Developer -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
